name: VIPPerms
version: '${project.version}'
main: vip.marcel.vipperms.spigot.vipperms.VIPPerms
api-version: 1.15
authors: [ VIPMarcel ]
description: full configurable spigot permission and group system
